export const state = {
  enem: [],
  enemySprites: ["assets/red.png", "assets/enemy2.png", "assets/enemy3.png"],
  hero: {
    left: 0,
    top: 20,
    speed: 5,
  },
  startTime: null,
  elapsedSeconds: 0,
  lives: 3,
  level: 1,
  speed: 2,
  direction: 1,
  dropDistance: 20,
  keys: {},
  isPaused: false,
  isGameOver: false,
  bullets: [],
  enemyBullets: [],
  score: 0,
  lastShotTime: 0,
  lastEnemyShotTime: 0,
};
